source "https://rubygems.org"
gem "logger"
gem "irb"
gem "test-cmd.rb"
gem "json"
gem "activerecord"
gem "pg"
gem "standard", "~> 1.54"
gem "roda", "~> 3.104"
gem "rackup", "~> 2.3"
gem "falcon"
gem "roda-sse", "~> 0.3"
gem "rack-test", "~> 2.2"
gem "rspec"
gem "rake"
gem "yard"
gem "kramdown"
gem "kramdown-parser-gfm"
gem "redcarpet"
gem "rouge"
gem "tilt"
gem "llm.rb"
gem "xchan.rb"
gem "async"
gem "net-http-persistent"
gem "paranoia"
gem "roda-llm", github: "r-uby-dev/roda-llm"